linters:
  disable-all: true
  enable:
    - errcheck
    - golint
    - ineffassign
    - unconvert
    - misspell
    - govet
linters-settings:
  errcheck:
    ignore: fmt:.*,io/ioutil:^Read.*,github.com/spf13/viper:BindPFlag
  golint:
    min-confidence: 1.1
issues:
  exclude:
    - composite
run:
  tests: false
